import Head from 'next/head';
import Layout from '../components/Layout';
import AboutSec1 from '../components/AboutSec1';
import AboutSec3 from '../components/AboutSec3';
import Cover from '../components/Cover';

export default function About() {
	return (
		<div>
			<Head>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Layout route={'| About'}>
				<Cover name='About' />
				<AboutSec1 />
				<AboutSec3 />
			</Layout>
		</div>
	);
}
