import Head from 'next/head';
import Layout from '../components/Layout';
import PorfolioIntro from '../components/PorfolioIntro';

export default function Porfolio() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Layout>
				{/* <section>hello ok</section> */}
				<PorfolioIntro />
			</Layout>
		</div>
	);
}
