import Head from 'next/head';
import InstaFeed from './components/InstaFeed';
import Layout from '../components/Layout';

export default function Porfolio() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Layout>
				<InstaFeed />
			</Layout>
		</div>
	);
}
